name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Swift version
        run: swift --version
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Install gems
        run: gem install colorize os sem_version ffi json
      - name: Install gem xcpretty
        run: gem install xcpretty -v 0.3
      - uses: KyleMayes/install-llvm-action@v2
        with:
          version: "15" # TODO: platform dependent (https://github.com/KyleMayes/install-llvm-action/blob/master/assets.json)
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Install cargo-swift
        if: matrix.os == 'macos-latest'
        run: cargo install cargo-swift
      - name: build
        if: matrix.os == 'macos-latest' || matrix.os == 'linux-latest'
        run: NO_PROMPTS=1 ruby build.rb all debug
      - name: Set environment variable on Windows
        if: matrix.os == 'windows-latest'
        run: echo "NO_PROMPTS=1" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: build Windows
        if: matrix.os == 'windows-latest'
        run: ruby build.rb all debug
      - name: test
        run: ruby test-report.rb
